# Generated by Django 3.1.3 on 2020-11-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20201121_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favourite_category',
            field=models.ManyToManyField(null=True, to='news.Category'),
        ),
    ]
