# Generated by Django 3.1.3 on 2020-11-23 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20201123_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_pic',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
